### PR TITLE
[UI] Employee Menu and Search screen

### PR DESCRIPTION
**Pull request by alebricio**
### This is a Partial Contribution addressing issue #107.
- Mobile and Desktop responsive as per Figma files.
- Adding View for Employee Menu and Search Bar.

View_1
View_3
View_1Desktop
View_2Desktop

### CODE REVIEW

**Comment by kanwalnainsingh** [comment]
@alebricio this looks good look, I think you are still making changes, let me know when it is ready for final review and merge.

**Comment by alebricio** [comment]
@kanwalnainsingh Code is ready for review. 👍 
Let me know if you'd like for me to make any changes!

**Comment by kanwalnainsingh** [comment]
Changes look great @alebricio  can you help me test and run this, Is there a route to test?

**Review by kanwalnainsingh — APPROVED** [review]

**Comment by kanwalnainsingh** [comment]
> Changes look great @alebricio can you help me test and run this, Is there a route to test?

able to test changes looks perfect.

**Pull request merged**
